import sqlite3

conn = sqlite3.connect('db.sqlite3')
c = conn.cursor()

c.executescript(
"""
insert into tutorials_tutorial (title, description, published) values ('I Think We''re Alone Now', '1JWY7R6nkmg4kC9CjtuLbEVpHB57uKxH69', false);
insert into tutorials_tutorial (title, description, published) values ('Rocks (Rad, Das)', '1Ppa9ETNqPW6tynBecHWWR2KBpoEptXUui', true);
insert into tutorials_tutorial (title, description, published) values ('Perrier''s Bounty', '13EjnW8geuTv6rag969xvvuLAanSHW7g3p', false);
insert into tutorials_tutorial (title, description, published) values ('Our Family Wedding', '1MUSYPnSjk6P9PSnEtRgST7nECKunDVb7E', true);
insert into tutorials_tutorial (title, description, published) values ('Night Moves', '15yrZ7rYTDxFPcLqpeysnULqjBXgNXK6t1', false);
insert into tutorials_tutorial (title, description, published) values ('SSSSSSS', '18JEhJD1yiAaHHwytW51Uefq1J8bCGZsDx', false);
insert into tutorials_tutorial (title, description, published) values ('Shadow Magic', '19LsgeRwBoLbdwgWBqaLzXToA7bvbW4Zct', true);
insert into tutorials_tutorial (title, description, published) values ('National Security', '1CqKf9W9YLoATkSyZ9yvuXCWQm8TCKHAEJ', true);
insert into tutorials_tutorial (title, description, published) values ('Barefoot', '1CFUKkb3QUrvCS1icwbubavW2EZu2nPQDe', false);
insert into tutorials_tutorial (title, description, published) values ('Russell Peters: The Green Card Tour - Live from the O2 Arena', '17N22eFj9LTAJ4fCP2eqcr7eHQgNLezf4o', true);
insert into tutorials_tutorial (title, description, published) values ('Flaming Star', '1LkxQsXNu9C7e6UmCbKMdbQcEt2gByPEmB', true);
insert into tutorials_tutorial (title, description, published) values ('Lesson in Love, A (En lektion i kärlek)', '1AdquwAA8i3eRaiZn8sNBw6GGxnuavww8U', false);
insert into tutorials_tutorial (title, description, published) values ('Yojimbo', '17iEP6YVTXMN7KuYiZhXpzqd6qpQhHuktv', true);
insert into tutorials_tutorial (title, description, published) values ('Land Before Time II: The Great Valley Adventure, The', '161Gd2EzRugNtEgTwAJEhjSemge4gfa8Eb', true);
insert into tutorials_tutorial (title, description, published) values ('Winds of the Wasteland', '1DeNJWYo1yfDhwbn5iswqpQ1z8jGWDCc4M', false);
insert into tutorials_tutorial (title, description, published) values ('Guy X', '1MZLmG1ZmkHWcaELR4qdastVPsPeuhjeyB', false);
insert into tutorials_tutorial (title, description, published) values ('Carry On Teacher', '1PnEZY18FHPv3zrbw8ha4oFpV7F7FuHd6s', true);
insert into tutorials_tutorial (title, description, published) values ('Eight Iron Men', '1CyTFbtXyi74Ci9435yhzvFKNPjLDfZ3GF', true);
insert into tutorials_tutorial (title, description, published) values ('This Happy Breed', '157ekYWGDuACgGrjtwpzRgVhTVW6sGsCNE', false);
insert into tutorials_tutorial (title, description, published) values ('Vanity Fair', '1JfdRvroXNDZFDAVyFhqC9SzNzJEwx4b9u', true);
insert into tutorials_tutorial (title, description, published) values ('Collapse', '18TweaVNCzFQ1JkrQCMLFtSudwqh8wyPmi', false);
insert into tutorials_tutorial (title, description, published) values ('Flamenco (de Carlos Saura)', '1PqihE5DCiDH3rPpnJAxeDXLLvk7RNERet', true);
insert into tutorials_tutorial (title, description, published) values ('Loins of Punjab Presents', '1ELFMijxCXytWgQCHn6QQk7yhCpzXEp55B', true);
insert into tutorials_tutorial (title, description, published) values ('Albino Farm', '17oQn5sAT31yq5d7HSKkm1bAEgyoV4Dnuw', false);
insert into tutorials_tutorial (title, description, published) values ('Shorts', '1DNuYxWALsoZrLVvyST4EWqzHPwGfUvPdy', true);
insert into tutorials_tutorial (title, description, published) values ('Dersu Uzala', '1FXejq4Ji9BubxAeKDe5fZm47E1ASpG6Mx', false);
insert into tutorials_tutorial (title, description, published) values ('Mom and Dad Save the World', '1JnDnHTinbHZBT26gaG2ncNsrZQHPswsVA', false);
insert into tutorials_tutorial (title, description, published) values ('How to Make an American Quilt', '1PCjX2vZeDVZf28ykb7WmNX4G9Xg5yjuAU', true);
insert into tutorials_tutorial (title, description, published) values ('Barfi!', '14rSbW4DgeiZcdM27M4Hiio3ZQtNViiWiM', false);
insert into tutorials_tutorial (title, description, published) values ('Zatoichi on the Road (Zatôichi kenka-tabi) (Zatôichi 5)', '15Gvc6H3TMBnFWe7cLNPnGipgcqJZNQaRp', false);
insert into tutorials_tutorial (title, description, published) values ('Daisy Kenyon', '1EQxzhvy35zxTBtgEyj87nV7g7cK55QmwG', true);
insert into tutorials_tutorial (title, description, published) values ('Lord of Illusions', '1C5LhMLLFRXQsyTA9b6a5sZZimRifKSyF6', false);
insert into tutorials_tutorial (title, description, published) values ('Seven Swords (Chat gim)', '19t1g8DSHnkMvKsi966pu7mGmiF2tu5bn6', true);
insert into tutorials_tutorial (title, description, published) values ('Brighton Beach Memoirs', '1A5zTCCMifVHZqF1qy5geWqHqvfknPTN1w', false);
insert into tutorials_tutorial (title, description, published) values ('Not Easily Broken', '1Ar97QFQ2KNMAvb8uaLMxZs5oy5qCyjzag', false);
insert into tutorials_tutorial (title, description, published) values ('Jack Frost', '1Q5JPLFLyLgejxJ7GXSGMdfPWSLEVzx7x4', true);
insert into tutorials_tutorial (title, description, published) values ('Burlesque', '1DUHYsUEx6mLKB6wAVfkoqVZmidjLoLrzE', false);
insert into tutorials_tutorial (title, description, published) values ('Waco: The Rules of Engagement', '12fLTVkMuiSU7fcJUoQxwYhAzDCbm53pzK', false);
insert into tutorials_tutorial (title, description, published) values ('Sometimes They Come Back', '1BsjNYk9kqmx3Gu31Vv1aDNuzthkd7EcPy', true);
insert into tutorials_tutorial (title, description, published) values ('King of Thorn (King of Thorns) (Ibara no O)', '14JmczBzkymxCsFNMxxNqaX5nQsVv4Np1D', true);
insert into tutorials_tutorial (title, description, published) values ('Saving Private Ryan', '1FywzPpuaRRsJPsAHa3GnEk3zBoeHQAByq', false);
insert into tutorials_tutorial (title, description, published) values ('May 18 (Hwaryeohan hyuga)', '12JfxvzTFBTMzLTvkHtZTL2seMwDghfs3s', true);
insert into tutorials_tutorial (title, description, published) values ('Out-of-Towners, The', '1ChFuSGeGVjEGGVQ65g55sPuLNR4kZrhFV', false);
insert into tutorials_tutorial (title, description, published) values ('Crimson Tide', '17pukbYNqLuuXHpdRuwh9EdWS6RMFUjHCW', false);
insert into tutorials_tutorial (title, description, published) values ('Leopard, The (Gattopardo, Il)', '1BjATW9ptKJos7hkUJQFaS6FugSCSh7YgE', false);
insert into tutorials_tutorial (title, description, published) values ('Headless Woman, The (Mujer sin cabeza, La)', '1M3oSbkh2oKndRYtjdXPYBgepvzQFVRyfw', false);
insert into tutorials_tutorial (title, description, published) values ('Child of Rage', '1BMMtRjjzRHKABMiB2Pkf1gC3c7ejFkDMw', true);
insert into tutorials_tutorial (title, description, published) values ('Unprecedented: The 2000 Presidential Election', '1JJzS1eHWk4QC8jJBjL7G9CbEiyiMQUV9X', false);
insert into tutorials_tutorial (title, description, published) values ('Gridiron Gang', '1GA36bTWFH97d3SgotxfXJDKNGAHiXMvGt', false);
insert into tutorials_tutorial (title, description, published) values ('Alive Inside', '132t2LHMwZWa7y7PHmTU3ctTUNZRQED4WT', false);
insert into tutorials_tutorial (title, description, published) values ('Three Guys Named Mike', '176codKF3A3hr3u9g4HoknMv4UX5GRYAHb', true);
insert into tutorials_tutorial (title, description, published) values ('White Sands', '1CiqB8NxjMwnyjM1tSNLBqaZ4A3jYxPzgf', false);
insert into tutorials_tutorial (title, description, published) values ('Sea of Grass, The', '19ZYf6hmsvHGvVKRYjn6qZ9qkybAUj8JEc', false);
insert into tutorials_tutorial (title, description, published) values ('Paperboy, The', '1KvTcEdzhux5cUB2uszi61ty95TDYa2iqN', false);
insert into tutorials_tutorial (title, description, published) values ('Luke and Lucy: The Texas Rangers (Suske en Wiske: De Texas rakkers)', '1LWXyw95Ls8mgyRwSWkb4qKuttEDMJZD4u', true);
insert into tutorials_tutorial (title, description, published) values ('It''s a Bikini World', '1FJbLJT4Bjr8fLsCjdxtSAH1uRrRHxdKvn', true);
insert into tutorials_tutorial (title, description, published) values ('9to5: Days in Porn (a.k.a. 9 to 5: Days in Porn)', '1B8Q17uiEJAGA2qJVv6pqiXNLZDjvaipsW', true);
insert into tutorials_tutorial (title, description, published) values ('Vali', '1Af5DnMcnh515zxwPanqUxTbdUdMrFmXyN', false);
insert into tutorials_tutorial (title, description, published) values ('Swimming with Sharks', '1CC5Z2yEpYUgS8j9L2CMJvfPWcWPHSqJBa', true);
insert into tutorials_tutorial (title, description, published) values ('Night Editor', '1P29YW4rkgZ4zw7TkUce5Fm2KByUnE3mPA', true);
insert into tutorials_tutorial (title, description, published) values ('Girls Gone Dead', '18D2kAD7x7ht9RKDiZCtBku1UuRUsEyroB', true);
insert into tutorials_tutorial (title, description, published) values ('Little Shop of Horrors, The', '15iVAirTGs9udTQ9hqcBnsB3h7cyqqGAVW', true);
insert into tutorials_tutorial (title, description, published) values ('Last Unicorn, The', '1FTXicibN3m73pA68sMmEXQD9jU58TQByr', true);
insert into tutorials_tutorial (title, description, published) values ('Half Past Dead', '1GGe4agpzCqs8w3gcHjM1odDP7UytGwzdi', false);
insert into tutorials_tutorial (title, description, published) values ('Hotel New Hampshire, The', '16C1745HwJo4BxAm4LGkD8aFomZLDJRkKk', false);
insert into tutorials_tutorial (title, description, published) values ('Bordertown', '1BukkmoyL4usowmQNEqpZeYjFDMsUUTmDy', false);
insert into tutorials_tutorial (title, description, published) values ('Cold Around the Heart', '1DEfDRjGXRWFgQVEPT9kEDaAtb5bVDaEmT', false);
insert into tutorials_tutorial (title, description, published) values ('Control', '1LMUHw6zPAZs4UsaQwZ3qmfJ68uNvXAFHS', false);
insert into tutorials_tutorial (title, description, published) values ('Cannonball', '1B6oZJhJpA1vBz23JRMijY67tXwLn3aqev', true);
insert into tutorials_tutorial (title, description, published) values ('Pride and Prejudice', '1J2a5EX1yPXkhC5haHoEJabsjaVx3LxU8r', false);
insert into tutorials_tutorial (title, description, published) values ('Young Frankenstein', '19HYRfggPFxkrBdD6zyY2zLGyG2RbDFa8i', true);
insert into tutorials_tutorial (title, description, published) values ('The Brave Little Toaster Goes to Mars', '1QGLiKmK8kWQUE5qkknGXdft7nfpFkr3R3', true);
insert into tutorials_tutorial (title, description, published) values ('Stars and Bars', '1Cuf1Ct9uM71hnHhoX7PZfystVx6aY7Ayi', true);
insert into tutorials_tutorial (title, description, published) values ('Welcome to Woop-Woop', '18P3TyynW9m9nHTAZoMeHcYtMy6f8tpDxD', true);
insert into tutorials_tutorial (title, description, published) values ('Dangerous Game', '1DNVZuCFUokV3emRjBbecUHjzNNhtzN5PK', false);
insert into tutorials_tutorial (title, description, published) values ('City of God (Cidade de Deus)', '198hWajdKuRddJFQvwxpZEKmPnG5RnThzr', false);
insert into tutorials_tutorial (title, description, published) values ('Something Wild', '1NgtF7RnBSxTSoTokjTRzcGY2MMwsSh3DH', true);
insert into tutorials_tutorial (title, description, published) values ('War on Democracy, The', '16N7dSqwvvzqQPgos8MFiAm6Dpr4E42T6n', false);
insert into tutorials_tutorial (title, description, published) values ('Voodoo Dawn', '1JPP32jxsu5dNjVx87X8uDSt4oEXZZ9qan', false);
insert into tutorials_tutorial (title, description, published) values ('Godzilla vs. Megalon (Gojira tai Megaro)', '18FeMi4H9x3XBnxoq5k45hDHKoYLSwmzMT', true);
insert into tutorials_tutorial (title, description, published) values ('Beauty and the Beast', '1AmbSUmD3MQEjzp1766GrwzZhpVNnGHugG', true);
insert into tutorials_tutorial (title, description, published) values ('Foodfight!', '1C3oodTfP7PpeZknNncvmBevp8XSSsnGGB', true);
insert into tutorials_tutorial (title, description, published) values ('Gitmek: My Marlon and Brando (Gitmek: Benim Marlon ve Brandom)', '1B4dCL5WVKXPjSQCJuZWVXrv4i6fheWsJi', true);
insert into tutorials_tutorial (title, description, published) values ('War Photographer', '19wNxuVrxAAPb8BxU1v4EzaboztQxB89LC', false);
insert into tutorials_tutorial (title, description, published) values ('Art of the Steal, The', '1JMEbajDacD1PZeC55t5QAskuy6sXpUdeu', true);
insert into tutorials_tutorial (title, description, published) values ('Cape Fear', '12DXdfdT3aV9ViKuQ748D1JkVMPsu3gpvc', true);
insert into tutorials_tutorial (title, description, published) values ('Flushed Away', '1JfsqHwAAUgykcVc3zESDBE6PSWmD1eeJ1', false);
insert into tutorials_tutorial (title, description, published) values ('Lost Youth', '1HdvhM7xyQKpV9ihcF8Ug9dff3fGcqbx9P', false);
insert into tutorials_tutorial (title, description, published) values ('Flicker (Flimmer)', '19bFCKREP7vqfTFiErqjosoWgdoB88BpkV', true);
insert into tutorials_tutorial (title, description, published) values ('Unconditional Love', '1CaFNDNmVJJWBZWxEGVbm5jjG7z9vocHEK', true);
insert into tutorials_tutorial (title, description, published) values ('Valet, The (La doublure)', '1D6X4Pw8vB3CZe4ufLNT5viG4VgdDCFnuD', true);
insert into tutorials_tutorial (title, description, published) values ('Wake in Providence, A', '13kFrv5285dYFxsL5ntBPjgKd5uLDUcwj8', true);
insert into tutorials_tutorial (title, description, published) values ('Kidnapping Mr. Heineken', '1PibPSVfjB3cAF1ZhJeUe868T3xnSsDPkP', true);
insert into tutorials_tutorial (title, description, published) values ('The Karen Carpenter Story', '1LqypQSogpQjCrpqPkcchj6kRQHggeGHmd', false);
insert into tutorials_tutorial (title, description, published) values ('Suriyothai (a.k.a. Legend of Suriyothai, The)', '1EALXTgc22it9jYLp3rpkWDCkCAyTZDA9u', true);
insert into tutorials_tutorial (title, description, published) values ('Lucky Jordan', '1DyUvTGUJZVd1zScRATRMhgSHqgYRSZPJy', false);
insert into tutorials_tutorial (title, description, published) values ('Motel Life, The', '18NSxCiK4iiGT49sbzxngrwuNNFJC5zRuu', false);
insert into tutorials_tutorial (title, description, published) values ('Queen, The', '138Zps49jEqMPv659pWFSH3mV257nLSgUo', true);
insert into tutorials_tutorial (title, description, published) values ('Glass Bottom Boat, The', '1CSdc7pZKWPYGybXsEcJhKwmQu9w5FY4Fa', true);
insert into tutorials_tutorial (title, description, published) values ('Where the Heart Is', '1KL2frYrN2tkRvKJNmMgiJ4tLTxoDeLudt', false);
insert into tutorials_tutorial (title, description, published) values ('Hi, Mom!', '12BQ4Hp52mnBUoXxAknSLznVtNjwEg1Vy5', true);
insert into tutorials_tutorial (title, description, published) values ('Snow White: A Tale of Terror', '1CdVd23LKRPjCowujL64zVAKZ4bWPaRVko', false);
insert into tutorials_tutorial (title, description, published) values ('Nines, The', '16T5RZu3MgDY8QCqGjT362vmT6oytEMNXN', false);
insert into tutorials_tutorial (title, description, published) values ('Chariots of the Gods (Erinnerungen an die Zukunft)', '1HQWmobEWDfJd15rNCuuKHiNU7VhQTCE1T', false);
insert into tutorials_tutorial (title, description, published) values ('Loft', '1HNrH3jaNfozThrZTNZQfFWczTLNCijLF4', true);
insert into tutorials_tutorial (title, description, published) values ('Rx', '1PFgZ8Pc8Nf2se3ZhL84qrDmxKwBHfFne9', false);
insert into tutorials_tutorial (title, description, published) values ('Tora! Tora! Tora!', '1KRnuPfZEY19hRE3XumeB1TbDvTtPX1CTd', false);
insert into tutorials_tutorial (title, description, published) values ('Crocodile Dundee in Los Angeles', '15q4Ev4VUE7PD7gtuKTRDHo7E8ZoJptBb4', true);
insert into tutorials_tutorial (title, description, published) values ('Dog Park', '19k6qbV1Z5teZNFiJ8WeDyC4A49aTK2L9U', false);
insert into tutorials_tutorial (title, description, published) values ('Madonna of the Seven Moons', '13D6ETgQdoKS3QR3EsqndnGPSNwjP1yT1v', false);
insert into tutorials_tutorial (title, description, published) values ('Ultramarathon Man: 50 Marathons, 50 States, 50 Days', '1KmkbneG24FPsnGRm1ZyczbeHLqWzGwbfh', false);
insert into tutorials_tutorial (title, description, published) values ('One Kill', '12LYapA3PjSgo83CEtVEszc2QUGdWZ9HVY', false);
insert into tutorials_tutorial (title, description, published) values ('Cave of Forgotten Dreams', '18a8wqjWxsDeThVESC4dLLyqY4B12NSXpz', false);
insert into tutorials_tutorial (title, description, published) values ('Babar The Movie', '13MCUEYQUwzdMQ31TEk1AVvRThdNbhtUvR', false);
insert into tutorials_tutorial (title, description, published) values ('Barney''s Version', '1MKCXaT82YGuEmDKxmq4vGdPDwQ29sgr42', false);
insert into tutorials_tutorial (title, description, published) values ('Quadrophenia', '1CowY4oksjcZEHU41VRoEbCpSx93VG8yW', false);
insert into tutorials_tutorial (title, description, published) values ('The Hound of the Baskervilles', '1JDo2xdP5frwprMRmCpF6RfctGZg1MQ5YM', false);
insert into tutorials_tutorial (title, description, published) values ('A Via Láctea', '14coqWX3oAPPPSKpGJbd9JCxFndBJLBFj8', true);
insert into tutorials_tutorial (title, description, published) values ('Henry V', '1H6YkPCcUX8c1xM1wAHKTfLK8CWTBeqNhT', false);
insert into tutorials_tutorial (title, description, published) values ('Mask of Fu Manchu, The', '1LBpJN5NhYcvW3B7LqaH8aevRTmCzFwD2m', true);
insert into tutorials_tutorial (title, description, published) values ('Ellen DeGeneres: The Beginning', '1YP3xGgNCaHfMwLs2zr6Gf3U5j2gGa6ZG', true);
insert into tutorials_tutorial (title, description, published) values ('Mantle', '18GdFoBuPbzvNKxgZ4e8EmnTBX3BFCeUvk', false);
insert into tutorials_tutorial (title, description, published) values ('John Dies at the End', '199UXnKyhZZb4JWzn15KXjK8Q1paPmd5n6', false);
insert into tutorials_tutorial (title, description, published) values ('Polytechnique', '1FRVcS3ZRZw4QTLEJVoVzBTNYgqKUjAMz3', false);
insert into tutorials_tutorial (title, description, published) values ('Stranded', '13qpF66hYp1DnMKuqGtWXARDXZhtbgBtqG', true);
insert into tutorials_tutorial (title, description, published) values ('The Fearmakers', '19VVDh8kidd9R1EC7xbLTsNsaNSmz2zNCh', true);
insert into tutorials_tutorial (title, description, published) values ('Battle of Britain, The (Why We Fight, 4)', '14oeNDRPs5WncPEC4RZ62yRwGS1E5GpeeT', true);
insert into tutorials_tutorial (title, description, published) values ('Won Ton Ton: The Dog Who Saved Hollywood', '12ij7KcHEwfNLjWvVAquxqndSBjR7xeZtC', true);
insert into tutorials_tutorial (title, description, published) values ('Trespass', '1E4Yipyt3GZaoTHqbp7rKPxomougEEwFM4', false);
insert into tutorials_tutorial (title, description, published) values ('Money Talks', '1QH6vYC632ekCeX1YczcLXE21YwcTmunmP', true);
insert into tutorials_tutorial (title, description, published) values ('Just Friends', '1Mxd3UnStEg5YCnevVbT8gvhUUeP2in4cE', false);
insert into tutorials_tutorial (title, description, published) values ('That Night''s Wife', '1Edqwq4j4KZn4cfsqXrRSzhv83txSyQQyi', true);
insert into tutorials_tutorial (title, description, published) values ('Hound of the Baskervilles, The', '14FQCZuA1T4iKwkUWafqMwLrxRLMjX8CiS', true);
insert into tutorials_tutorial (title, description, published) values ('Assault on Wall Street ', '17pnegZS57nYTUyg5qmWosvvtfuSitxaak', true);
insert into tutorials_tutorial (title, description, published) values ('Beautiful', '1HMp5HHfa5YRvvvdxDrSEF9dmYgALvRwdH', false);
insert into tutorials_tutorial (title, description, published) values ('First Descent', '1HpWL7vsj4ENyN4i1jp7ufvmnwvneHggLo', true);
insert into tutorials_tutorial (title, description, published) values ('Dead Leaves', '13znou1DvSLJwhib4quw5fuJqujLXekk15', false);
insert into tutorials_tutorial (title, description, published) values ('Cottage, The', '182Abpxq2E8nEawPN9jtxFujDyGRpa1puM', false);
insert into tutorials_tutorial (title, description, published) values ('Red Riding: 1974', '1FQPnJeaeZjTSvXp7PBvuQe91NjLkWDG1L', false);
insert into tutorials_tutorial (title, description, published) values ('Ghosts... of the Civil Dead', '1M8BLVXr2yBr54FrwcAPHKFzmyjc777QPR', false);
insert into tutorials_tutorial (title, description, published) values ('Eccentricities of a Blonde-haired Girl (Singularidades de uma Rapariga Loura)', '1NGPJMeBTLTq9BTjE9YBZYGEUJyu3PiegC', true);
insert into tutorials_tutorial (title, description, published) values ('Shaft''s Big Score!', '17pRDhmuokoULbqgpGCRbqJiavmw7yDPgv', false);
insert into tutorials_tutorial (title, description, published) values ('Beau Brummell: This Charming Man', '1QBSYa1R2ZoxgMP4RpqyKavRC3zqdvgmDu', true);
insert into tutorials_tutorial (title, description, published) values ('Contagion / Bio Slime', '1WbrKNNdh3sGnf2tmxJoum9KuoHkCR7my', true);
insert into tutorials_tutorial (title, description, published) values ('Jackal, The', '1G2zH4iK5HHyzkSkERSkc87wgVrv35yfPX', false);
insert into tutorials_tutorial (title, description, published) values ('Train on the Brain', '191uZuzx4W3kaZmwpqsFv1ZEAVvwjwmSA', false);
insert into tutorials_tutorial (title, description, published) values ('Hairspray', '1D26niXCjYy6nmRimxty1cNJPSJVtezfyU', true);
insert into tutorials_tutorial (title, description, published) values ('Beautiful Country, The', '1MrPfDxiJZuygLaFsdvG547Wrw2G1ZkhVY', true);
insert into tutorials_tutorial (title, description, published) values ('Day and Night (Dag och natt)', '1EWPTiLiwnekMnZKxZyrNzCZQypSNUzNwP', true);
insert into tutorials_tutorial (title, description, published) values ('Kaspar Hauser', '1Jeo9p4VLZtoLGLPqVD5VjtPFuiBDUgB5g', false);
"""
)

conn.commit()
conn.close()